server:
  port: 8080
  servlet:
    context-path: /appointment

spring:
  application:
    name: appointment-service
  config:
    import: optional:configserver:http://localhost:8888/

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:appointment-service;DB_CLOSE_DELAY=-1
    username: sa
  h2:
      console:
        enabled: true
        path: /h2-console
  sql:
    init:
      data-locations: classpath:init.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
