server:
  port: 8080

spring:
  application:
    name: dentist-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dentist-service;DB_CLOSE_DELAY=-1
    username: sa
  h2:
    console:
      enabled: true
  #sql:
  #  init:
  #    data-locations: classpath:init.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop


  config:
    import: optional:configserver:http://localhost:8888



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
